.PHONY: docker/build
docker/build:
	docker build --tag bryfly-web .

.PHONY: docker/start
docker/start: docker/build
	docker run -p 8000:8000 bryfly-web

.PHONY: docker/clean
docker/clean:
	docker container prune -f
