name: Check Next.js app

on:
  push:
    paths:
      - "app/**"
      - "lib/**"
      - "**.tsx?"
      - "**.jsx?"
      - "**.json"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          check-latest: true
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - name: Check code format
        run: pnpm run format --list-different
      - name: Run linter
        run: pnpm run lint
