name: Build Next App

on:
  push:
    paths:
      - "**.ts"
      - "**.tsx"
  pull_request:
    branches: [$default-branch]
    paths:
      - "**.ts"
      - "**.tsx"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported versions at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - name: Check code format
        run: |
          npm run lint:check
          npm run fmt:check
